### PR TITLE
Added prereq Role::Tiny as suggested by CPANTS.

### PR DESCRIPTION
**Pull request by manwar**
Hi @abraxxa 

Please review the PR.
https://cpants.cpanauthors.org/release/ABRAXXA/Net-Cisco-FMC-v1-0.004001

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by abraxxa** [comment]
I haven't specified that dist as requirement as it's an upstream dependency of Moo.

**Comment by manwar** [comment]
> I haven't specified that dist as requirement as it's an upstream dependency of Moo.

package Net::Cisco::FMC::v1::Role::FixAccessruleLiterals;

# ABSTRACT: Role for Cisco Firepower Management Center (FMC) API version 1 method generation

use 5.024;
use feature 'signatures';
use NetAddr::IP::Lite ':nofqdn';
use Role::Tiny;

no warnings "experimental::signatures";

**Comment by abraxxa** [comment]
Moo::Role also imports `apply_roles_to_object` so I'll use this instead.

**Comment by manwar** [comment]
It is always recommended to have all dependency listed explicitly.

**Pull request closed without merging**
